version: "3.9"

networks:
  avatars:
    driver: bridge

services:
  dnmonster:
    image: saddroopy/dnmonster:latest
    container_name: dnmonster_container
    ports:
      - "8080:8080"
    networks:
      - avatars

  avatar:
    build: .
    container_name: serv_container
    ports:
      - "3000:3000"
    environment:
      - ENV=DEV
      - IMAGE_GEN_HOST=dnmonster:8080/monster
      - REDIS_HOST=redis
    networks:
      - avatars
    depends_on:
      - dnmonster
    volumes:
      - ./src:/home/node/app/src
      - /home/node/app/node_modules
  redis:
    image: redis:6-bullseye
    hostname: redis
    networks:
      - avatars
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
