version: "3.9"

networks:
  avy-net:
    driver: bridge

services:
  dnmonster:
    image: saddroopy/dnmonster
    container_name: avatars_dbmonster_container
    ports:
      - "8080:8080"
    networks:
      - avy-net

  avatar:
    build: .
    container_name: avatars_serv_container
    ports:
      - "3000:3000"
    environment:
      - ENV=DEV
      - IMAGE_GEN_HOST=dnmonster:8080/monster
    networks:
      - avy-net
    depends_on:
      - dnmonster
    volumes:
      - ./src:/home/node/app/src
      - /home/node/app/node_modules
  redis:
    image: redis:3.0.5
